# Custom config for scss-lint
# Find an example of all options here: https://github.com/causes/scss-lint/blob/master/config/default.yml

exclude:
    - 'style.css'
    - 'vendor/**'

linters:
  Indentation:
    enabled: true
    width: 4

  NestingDepth:
    enabled: false

  PropertySortOrder:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 4

  StringQuotes:
    style: double_quotes

  SelectorFormat:
    enabled: false
    convention: BEM

  TrailingSemicolonAfterPropertyValue:
    enabled: false

  VendorPrefixes:
    enabled: false
